version: "3.8"

services:
  # React Frontend
  react-app:
    image: itskishore/frontend_react_roomsite
    container_name: react-app
    ports:
      - "5173:5173"
    networks:
      - app-network

  # Spring Boot Services
  customer-user-service:
    image: itskishore/user_ms_roomsite
    container_name: customer-user-service
    ports:
      - "8083:8083"
    networks:
      - app-network

  booking-service:
    image: itskishore/booking_ms_roomsite
    container_name: booking-service
    ports:
      - "8081:8081"
    networks:
      - app-network

  payment-service:
    image: itskishore/payment_ms_roomsite
    container_name: payment-service
    ports:
      - "8082:8082"
    networks:
      - app-network

  # Node.js Services
  host-service:
    image: itskishore/host_ms_roomsite
    container_name: host-service
    ports:
      - "8084:8084"
    networks:
      - app-network

  rooms-service:
    image: itskishore/room_ms_roomsite
    container_name: rooms-service
    ports:
      - "8086:8086"
    networks:
      - app-network

  report-service:
    image: itskishore/report_ms_roomsite
    container_name: report-service
    ports:
      - "8085:8085"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
